Update .gitignore to avoid conflict when updating version in Slicer
This commit will avoid error like the following:

```
error: Your local changes to the following files would be overwritten by checkout:
	setup.cfg
Please, commit your changes or stash them before you can switch branches.
Aborting

```